-- Migration: Seed patterns table with initial data
-- Description: Populates patterns for Levels 1-2 (free tier content)

-- Level 1: Foundation - Reductions (Patterns 1-10)
INSERT INTO public.patterns (id, category, level, title, description, phonetic_clear, phonetic_reduced, example_sentence, example_transcription, audio_slow_url, audio_fast_url, tips, difficulty, order_index) VALUES
('reduction-wanna', 'reductions', 1, 'Want to → Wanna', 'In casual speech, "want to" is almost always pronounced as "wanna". This is one of the most common reductions in English.', '/wɑːnt tuː/', '/wɑːnə/', 'I want to go home.', 'I wanna go home.', '/audio/patterns/reduction-wanna-slow.mp3', '/audio/patterns/reduction-wanna-fast.mp3', ARRAY['Listen for the "t" sound disappearing completely', 'The "to" becomes a quick "uh" sound (schwa)', 'This reduction happens in questions too: "Do you wanna...?"'], 1, 1),

('reduction-gonna', 'reductions', 1, 'Going to → Gonna', 'When talking about future plans or intentions, "going to" becomes "gonna". You''ll hear this in almost every casual English conversation.', '/ˈɡoʊɪŋ tuː/', '/ˈɡʌnə/', 'I''m going to call her later.', 'I''m gonna call her later.', '/audio/patterns/reduction-gonna-slow.mp3', '/audio/patterns/reduction-gonna-fast.mp3', ARRAY['The "going" loses its "-ing" ending', 'Focus on the "guh-nuh" sound', 'Often combined with contractions: "I''m gonna", "We''re gonna"'], 1, 2),

('reduction-hafta', 'reductions', 1, 'Have to → Hafta', '"Have to" expressing obligation becomes "hafta" in natural speech. The "v" sound transforms into an "f" sound.', '/hæv tuː/', '/ˈhæftə/', 'I have to leave now.', 'I hafta leave now.', '/audio/patterns/reduction-hafta-slow.mp3', '/audio/patterns/reduction-hafta-fast.mp3', ARRAY['The "v" changes to an "f" sound', 'The "to" becomes a schwa sound', 'Also applies to "has to" → "hasta"'], 1, 3),

('reduction-gotta', 'reductions', 1, 'Got to → Gotta', '"Got to" meaning "have to" or "must" reduces to "gotta". Very common in American English.', '/ɡɒt tuː/', '/ˈɡɑːtə/', 'I''ve got to go.', 'I''ve gotta go.', '/audio/patterns/reduction-gotta-slow.mp3', '/audio/patterns/reduction-gotta-fast.mp3', ARRAY['The "t" at the end of "got" becomes a flap', 'The "to" reduces to a schwa', 'Often shortened further to "I gotta" without "have"'], 1, 4),

('reduction-kinda', 'reductions', 1, 'Kind of → Kinda', '"Kind of" used as a softener or approximation becomes "kinda". Extremely common in casual speech.', '/kaɪnd ɒv/', '/ˈkaɪndə/', 'It''s kind of cold today.', 'It''s kinda cold today.', '/audio/patterns/reduction-kinda-slow.mp3', '/audio/patterns/reduction-kinda-fast.mp3', ARRAY['The "of" completely disappears', 'The "d" connects directly to the schwa', 'Used to soften statements or express uncertainty'], 1, 5),

('reduction-lotta', 'reductions', 1, 'Lot of → Lotta', '"A lot of" reduces to "a lotta" with the "of" sound nearly disappearing.', '/lɒt ɒv/', '/ˈlɑːtə/', 'There are a lot of people here.', 'There are a lotta people here.', '/audio/patterns/reduction-lotta-slow.mp3', '/audio/patterns/reduction-lotta-fast.mp3', ARRAY['The "of" reduces to just a schwa', 'The "t" often becomes a flap sound', 'Sometimes even further reduced in very fast speech'], 2, 6),

('reduction-outta', 'reductions', 1, 'Out of → Outta', '"Out of" becomes "outta" in casual speech. The "f" sound of "of" disappears entirely.', '/aʊt ɒv/', '/ˈaʊtə/', 'Get out of here!', 'Get outta here!', '/audio/patterns/reduction-outta-slow.mp3', '/audio/patterns/reduction-outta-fast.mp3', ARRAY['The "of" loses its consonant sound', 'The "t" connects to the schwa', 'Common in phrases like "outta time", "outta luck"'], 2, 7),

('reduction-sorta', 'reductions', 1, 'Sort of → Sorta', '"Sort of" meaning "kind of" or "somewhat" reduces to "sorta".', '/sɔːrt ɒv/', '/ˈsɔːrtə/', 'I sort of understand.', 'I sorta understand.', '/audio/patterns/reduction-sorta-slow.mp3', '/audio/patterns/reduction-sorta-fast.mp3', ARRAY['Similar pattern to "kinda"', 'The "of" disappears completely', 'Interchangeable with "kinda" in most contexts'], 2, 8),

('reduction-coulda', 'reductions', 1, 'Could have → Coulda', '"Could have" in past conditionals reduces to "coulda". Never confuse this with "could of" - it''s always "could have"!', '/kʊd hæv/', '/ˈkʊdə/', 'I could have helped.', 'I coulda helped.', '/audio/patterns/reduction-coulda-slow.mp3', '/audio/patterns/reduction-coulda-fast.mp3', ARRAY['The "have" completely reduces to a schwa', 'This is "could have", not "could of"', 'Same pattern for "woulda" and "shoulda"'], 2, 9),

('reduction-lemme', 'reductions', 1, 'Let me → Lemme', '"Let me" at the start of requests becomes the quick "lemme".', '/let miː/', '/ˈlemi/', 'Let me see that.', 'Lemme see that.', '/audio/patterns/reduction-lemme-slow.mp3', '/audio/patterns/reduction-lemme-fast.mp3', ARRAY['The "t" disappears and words merge', 'Very common at the start of sentences', 'Shows informal, friendly tone'], 1, 10);

-- Level 1: Foundation - Weak Forms (Patterns 11-20)
INSERT INTO public.patterns (id, category, level, title, description, phonetic_clear, phonetic_reduced, example_sentence, example_transcription, audio_slow_url, audio_fast_url, tips, difficulty, order_index) VALUES
('weak-to', 'weak-forms', 1, 'The weak form of "to"', 'In unstressed positions, "to" changes from /tuː/ to /tə/. This is one of the most frequent weak forms in English.', '/tuː/', '/tə/', 'I need to go to the store.', 'I need tə go tə the store.', '/audio/patterns/weak-to-slow.mp3', '/audio/patterns/weak-to-fast.mp3', ARRAY['Listen for the quick "tuh" sound', 'The vowel becomes a schwa', 'Only stressed when emphasizing: "I said TO the store, not FROM"'], 1, 11),

('weak-for', 'weak-forms', 1, 'The weak form of "for"', '"For" reduces from /fɔːr/ to /fər/ in most sentences, sounding almost like "fer".', '/fɔːr/', '/fər/', 'This is for you.', 'This is fər you.', '/audio/patterns/weak-for-slow.mp3', '/audio/patterns/weak-for-fast.mp3', ARRAY['Sounds like "fer" in fast speech', 'The vowel shortens significantly', 'Strong form used only for emphasis'], 1, 12),

('weak-of', 'weak-forms', 1, 'The weak form of "of"', '"Of" rarely sounds like "ov" in natural speech. It typically reduces to /əv/ or even just /ə/.', '/ɒv/', '/əv/', 'A cup of coffee.', 'A cup əv coffee.', '/audio/patterns/weak-of-slow.mp3', '/audio/patterns/weak-of-fast.mp3', ARRAY['Often sounds like just "uh"', 'The "v" may barely be heard', 'Very common in phrases: "kind of", "sort of", "lot of"'], 1, 13),

('weak-and', 'weak-forms', 1, 'The weak form of "and"', '"And" reduces dramatically from /ænd/ to /ənd/, /ən/, or even just /n/.', '/ænd/', '/ən/', 'Bread and butter.', 'Bread ən butter.', '/audio/patterns/weak-and-slow.mp3', '/audio/patterns/weak-and-fast.mp3', ARRAY['Can sound like just "n" between words', 'The "d" often disappears', 'Listen for it in lists and compound phrases'], 1, 14),

('weak-the', 'weak-forms', 1, 'The weak form of "the"', '"The" is pronounced /ðə/ before consonants and /ði/ before vowels, but both are unstressed and quick.', '/ðiː/', '/ðə/', 'The book is on the table.', 'Thə book is on thə table.', '/audio/patterns/weak-the-slow.mp3', '/audio/patterns/weak-the-fast.mp3', ARRAY['Before consonants: "thuh"', 'Before vowels: "thee" (but still quick)', 'Never stressed unless emphasizing: "THE solution"'], 1, 15),

('weak-a', 'weak-forms', 1, 'The weak form of "a"', 'The article "a" is always pronounced as a schwa /ə/ in normal speech, never as /eɪ/.', '/eɪ/', '/ə/', 'I saw a movie.', 'I saw ə movie.', '/audio/patterns/weak-a-slow.mp3', '/audio/patterns/weak-a-fast.mp3', ARRAY['Always sounds like "uh", never "ay"', 'The "ay" sound is only for spelling out the letter', 'Connects smoothly to the following word'], 1, 16),

('weak-him', 'weak-forms', 1, 'The weak form of "him"', '"Him" loses its /h/ in connected speech, becoming just /ɪm/.', '/hɪm/', '/ɪm/', 'Tell him to come.', 'Tell im to come.', '/audio/patterns/weak-him-slow.mp3', '/audio/patterns/weak-him-fast.mp3', ARRAY['The "h" disappears in fast speech', 'Sounds like "im" attached to previous word', 'Called "h-dropping" - very common in connected speech'], 2, 17),

('weak-her', 'weak-forms', 1, 'The weak form of "her"', '"Her" reduces from /hɜːr/ to /ər/, losing both the /h/ and the vowel length.', '/hɜːr/', '/ər/', 'Give her the book.', 'Give ər the book.', '/audio/patterns/weak-her-slow.mp3', '/audio/patterns/weak-her-fast.mp3', ARRAY['Sounds like just "er" in fast speech', 'The "h" is dropped like in "him"', 'Can be very hard to hear in rapid speech'], 2, 18),

('weak-them', 'weak-forms', 1, 'The weak form of "them"', '"Them" reduces to /əm/ in casual speech, sometimes written as ''em.', '/ðem/', '/əm/', 'Tell them the news.', 'Tell ''em the news.', '/audio/patterns/weak-them-slow.mp3', '/audio/patterns/weak-them-fast.mp3', ARRAY['The "th" often disappears', 'Sounds like "um" or "em"', 'Written as ''em in informal contexts'], 2, 19),

('weak-can', 'weak-forms', 1, 'The weak form of "can"', '"Can" reduces from /kæn/ to /kən/ in positive statements. This contrasts with "can''t" /kænt/.', '/kæn/', '/kən/', 'I can help you.', 'I kən help you.', '/audio/patterns/weak-can-slow.mp3', '/audio/patterns/weak-can-fast.mp3', ARRAY['Weak "can" sounds like "kun"', 'Strong "can''t" keeps the full vowel', 'Distinguishing can/can''t relies on this difference!'], 2, 20);

-- Level 2: Common Reductions - More Weak Forms (Patterns 21-30)
INSERT INTO public.patterns (id, category, level, title, description, phonetic_clear, phonetic_reduced, example_sentence, example_transcription, audio_slow_url, audio_fast_url, tips, difficulty, order_index) VALUES
('weak-was', 'weak-forms', 2, 'The weak form of "was"', '"Was" reduces from /wɒz/ to /wəz/ in unstressed positions.', '/wɒz/', '/wəz/', 'She was happy.', 'She wəz happy.', '/audio/patterns/weak-was-slow.mp3', '/audio/patterns/weak-was-fast.mp3', ARRAY['The vowel becomes a schwa', 'Strong form used for emphasis or contrast', 'Listen for "wuz" in natural speech'], 2, 21),

('weak-were', 'weak-forms', 2, 'The weak form of "were"', '"Were" reduces from /wɜːr/ to /wər/, sounding almost like "wer".', '/wɜːr/', '/wər/', 'They were late.', 'They wər late.', '/audio/patterns/weak-were-slow.mp3', '/audio/patterns/weak-were-fast.mp3', ARRAY['Sounds like a quick "wer"', 'The vowel shortens significantly', 'Can sound similar to "was" in very fast speech'], 2, 22),

('weak-are', 'weak-forms', 2, 'The weak form of "are"', '"Are" reduces from /ɑːr/ to /ər/, often merging with the previous word.', '/ɑːr/', '/ər/', 'Where are you going?', 'Where ər you going?', '/audio/patterns/weak-are-slow.mp3', '/audio/patterns/weak-are-fast.mp3', ARRAY['Sounds like just "er" in fast speech', 'Often contracted: "Where''re you"', 'Almost disappears after "we", "you", "they"'], 2, 23),

('weak-have', 'weak-forms', 2, 'The weak form of "have"', '"Have" as an auxiliary reduces from /hæv/ to /həv/ or /əv/.', '/hæv/', '/əv/', 'I have seen it.', 'I''ve seen it. / I əv seen it.', '/audio/patterns/weak-have-slow.mp3', '/audio/patterns/weak-have-fast.mp3', ARRAY['The "h" is often dropped', 'Becomes "uv" sound in fast speech', 'Explains "coulda/woulda/shoulda" reductions'], 2, 24),

('weak-has', 'weak-forms', 2, 'The weak form of "has"', '"Has" as an auxiliary reduces from /hæz/ to /həz/ or /əz/.', '/hæz/', '/əz/', 'She has finished.', 'She''s finished. / She əz finished.', '/audio/patterns/weak-has-slow.mp3', '/audio/patterns/weak-has-fast.mp3', ARRAY['Usually contracted to "''s" in speech', 'The full form sounds like "uz" when reduced', 'Hard to distinguish from "is" - context helps'], 2, 25),

('weak-had', 'weak-forms', 2, 'The weak form of "had"', '"Had" as an auxiliary reduces from /hæd/ to /həd/ or /əd/.', '/hæd/', '/əd/', 'I had already left.', 'I''d already left. / I əd already left.', '/audio/patterns/weak-had-slow.mp3', '/audio/patterns/weak-had-fast.mp3', ARRAY['Usually contracted to "''d" in speech', 'Sounds like "ud" when reduced', 'Same contraction as "would" - context is key'], 2, 26),

('weak-do', 'weak-forms', 2, 'The weak form of "do"', '"Do" in questions and negatives reduces from /duː/ to /də/ or /d/.', '/duː/', '/də/', 'What do you think?', 'What də you think?', '/audio/patterns/weak-do-slow.mp3', '/audio/patterns/weak-do-fast.mp3', ARRAY['Sounds like "duh" in questions', 'Can merge with "you": "d''you think?"', 'Strong form only for emphasis'], 2, 27),

('weak-does', 'weak-forms', 2, 'The weak form of "does"', '"Does" reduces from /dʌz/ to /dəz/.', '/dʌz/', '/dəz/', 'What does he want?', 'What dəz he want?', '/audio/patterns/weak-does-slow.mp3', '/audio/patterns/weak-does-fast.mp3', ARRAY['Sounds like "duz" in fast speech', 'The vowel becomes a schwa', 'Can be hard to hear in rapid questions'], 2, 28),

('weak-at', 'weak-forms', 2, 'The weak form of "at"', '"At" reduces from /æt/ to /ət/ in most contexts.', '/æt/', '/ət/', 'Look at this!', 'Look ət this!', '/audio/patterns/weak-at-slow.mp3', '/audio/patterns/weak-at-fast.mp3', ARRAY['Sounds like "ut" in connected speech', 'Merges with previous word smoothly', 'Strong form only when emphasized'], 2, 29),

('weak-from', 'weak-forms', 2, 'The weak form of "from"', '"From" reduces from /frɒm/ to /frəm/, with a quick schwa.', '/frɒm/', '/frəm/', 'I''m from Brazil.', 'I''m frəm Brazil.', '/audio/patterns/weak-from-slow.mp3', '/audio/patterns/weak-from-fast.mp3', ARRAY['The vowel shortens to a schwa', 'Sounds like "frum" in fast speech', 'Stronger when contrasting: "FROM, not TO"'], 2, 30);

-- Level 2: Common Reductions - Assimilation Patterns (Patterns 31-40)
INSERT INTO public.patterns (id, category, level, title, description, phonetic_clear, phonetic_reduced, example_sentence, example_transcription, audio_slow_url, audio_fast_url, tips, difficulty, order_index) VALUES
('assimilation-doncha', 'assimilation', 2, 'Don''t you → Doncha', 'When "don''t" meets "you", the sounds merge to create "doncha".', '/doʊnt juː/', '/ˈdoʊntʃə/', 'Don''t you think so?', 'Doncha think so?', '/audio/patterns/assimilation-doncha-slow.mp3', '/audio/patterns/assimilation-doncha-fast.mp3', ARRAY['The "t" and "y" combine into a "ch" sound', 'This is called palatalization', 'Very common in questions'], 2, 31),

('assimilation-wontcha', 'assimilation', 2, 'Won''t you → Wontcha', 'Similar to "doncha", "won''t you" becomes "wontcha" in casual speech.', '/woʊnt juː/', '/ˈwoʊntʃə/', 'Won''t you stay?', 'Wontcha stay?', '/audio/patterns/assimilation-wontcha-slow.mp3', '/audio/patterns/assimilation-wontcha-fast.mp3', ARRAY['Same "ch" sound as "doncha"', 'The "y" of "you" triggers the change', 'Common in invitations and requests'], 2, 32),

('assimilation-couldja', 'assimilation', 2, 'Could you → Couldja', '"Could you" merges into "couldja" with the "d" and "y" combining.', '/kʊd juː/', '/ˈkʊdʒə/', 'Could you help me?', 'Couldja help me?', '/audio/patterns/assimilation-couldja-slow.mp3', '/audio/patterns/assimilation-couldja-fast.mp3', ARRAY['The "d" and "y" create a "j" sound', 'Same pattern in "would you" → "wouldja"', 'Very common in polite requests'], 2, 33),

('assimilation-wouldja', 'assimilation', 2, 'Would you → Wouldja', '"Would you" becomes "wouldja" following the same pattern as "couldja".', '/wʊd juː/', '/ˈwʊdʒə/', 'Would you like some?', 'Wouldja like some?', '/audio/patterns/assimilation-wouldja-slow.mp3', '/audio/patterns/assimilation-wouldja-fast.mp3', ARRAY['The "d+y" creates a "j" sound', 'Extremely common in offers and questions', 'Sometimes reduced further to "wudja"'], 2, 34),

('assimilation-didja', 'assimilation', 2, 'Did you → Didja', '"Did you" becomes "didja" in fast speech, very common in questions.', '/dɪd juː/', '/ˈdɪdʒə/', 'Did you see that?', 'Didja see that?', '/audio/patterns/assimilation-didja-slow.mp3', '/audio/patterns/assimilation-didja-fast.mp3', ARRAY['Same "d+y" → "j" pattern', 'Often further reduced to "dja"', 'Listen for it in past tense questions'], 2, 35),

('assimilation-gotcha', 'assimilation', 2, 'Got you → Gotcha', '"Got you" meaning "I understand" or "I caught you" becomes "gotcha".', '/ɡɒt juː/', '/ˈɡɑːtʃə/', 'I got you! / Got you.', 'Gotcha!', '/audio/patterns/assimilation-gotcha-slow.mp3', '/audio/patterns/assimilation-gotcha-fast.mp3', ARRAY['The "t+y" creates a "ch" sound', 'Used to mean "I understand" or "I tricked you"', 'Very informal and friendly'], 2, 36),

('assimilation-betcha', 'assimilation', 2, 'Bet you → Betcha', '"I bet you" reduces to "I betcha" in casual speech.', '/bet juː/', '/ˈbetʃə/', 'I bet you can''t!', 'I betcha can''t!', '/audio/patterns/assimilation-betcha-slow.mp3', '/audio/patterns/assimilation-betcha-fast.mp3', ARRAY['The "t+y" creates a "ch" sound', 'Common in challenges and predictions', 'Informal, playful tone'], 3, 37),

('assimilation-letcha', 'assimilation', 2, 'Let you → Letcha', '"Let you" becomes "letcha" when spoken quickly.', '/let juː/', '/ˈletʃə/', 'I''ll let you know.', 'I''ll letcha know.', '/audio/patterns/assimilation-letcha-slow.mp3', '/audio/patterns/assimilation-letcha-fast.mp3', ARRAY['Same "t+y" → "ch" pattern', 'Common in promises and offers', 'Sometimes preceded by reduced "I''ll"'], 3, 38),

('assimilation-meetcha', 'assimilation', 2, 'Meet you → Meetcha', '"Meet you" and "Nice to meet you" often sound like "meetcha".', '/miːt juː/', '/ˈmiːtʃə/', 'Nice to meet you!', 'Nice to meetcha!', '/audio/patterns/assimilation-meetcha-slow.mp3', '/audio/patterns/assimilation-meetcha-fast.mp3', ARRAY['The "t+y" merges to "ch"', 'Very common in greetings', 'Full phrase often: "Nice ta meetcha"'], 2, 39),

('assimilation-whatcha', 'assimilation', 2, 'What are you → Whatcha', '"What are you" collapses to just "whatcha" in casual questions.', '/wɒt ɑːr juː/', '/ˈwʌtʃə/', 'What are you doing?', 'Whatcha doing?', '/audio/patterns/assimilation-whatcha-slow.mp3', '/audio/patterns/assimilation-whatcha-fast.mp3', ARRAY['Three words become one', 'The "are" completely disappears', 'Extremely common in everyday questions'], 2, 40);

-- Level 2: Common Reductions - Linking Patterns (Patterns 41-50)
INSERT INTO public.patterns (id, category, level, title, description, phonetic_clear, phonetic_reduced, example_sentence, example_transcription, audio_slow_url, audio_fast_url, tips, difficulty, order_index) VALUES
('linking-cv-turnoff', 'linking', 2, 'Consonant-Vowel Linking: turn off', 'When a word ending in a consonant is followed by a word starting with a vowel, they link smoothly.', '/tɜːrn ɒf/', '/tɜːr.nɒf/', 'Turn off the light.', 'Tur-noff the light.', '/audio/patterns/linking-cv-turnoff-slow.mp3', '/audio/patterns/linking-cv-turnoff-fast.mp3', ARRAY['The "n" connects to "off"', 'No pause between words', 'Creates smooth, connected speech'], 2, 41),

('linking-cv-pickup', 'linking', 2, 'Consonant-Vowel Linking: pick up', 'The final consonant of "pick" links directly to "up".', '/pɪk ʌp/', '/pɪ.kʌp/', 'Pick up the phone.', 'Pi-kup the phone.', '/audio/patterns/linking-cv-pickup-slow.mp3', '/audio/patterns/linking-cv-pickup-fast.mp3', ARRAY['The "k" attaches to "up"', 'Sounds like one word: "pickup"', 'Very common with phrasal verbs'], 2, 42),

('linking-cv-itis', 'linking', 2, 'Consonant-Vowel Linking: it is', '"It is" links to sound almost like "itis".', '/ɪt ɪz/', '/ɪ.tɪz/', 'It is important.', 'I-tis important.', '/audio/patterns/linking-cv-itis-slow.mp3', '/audio/patterns/linking-cv-itis-fast.mp3', ARRAY['The "t" connects to "is"', 'In American English, often a flap: "idiz"', 'Usually contracted to "It''s" anyway'], 2, 43),

('linking-cv-checkit', 'linking', 2, 'Consonant-Vowel Linking: check it', '"Check it" links smoothly with the "k" connecting to "it".', '/tʃek ɪt/', '/tʃe.kɪt/', 'Check it out!', 'Che-kit out!', '/audio/patterns/linking-cv-checkit-slow.mp3', '/audio/patterns/linking-cv-checkit-fast.mp3', ARRAY['The "k" connects to "it"', 'Sounds like "checkit"', 'Common phrase in casual speech'], 2, 44),

('linking-cv-notat', 'linking', 2, 'Consonant-Vowel Linking: not at', '"Not at" links with the "t" connecting to "at".', '/nɒt æt/', '/nɒ.tæt/', 'I''m not at home.', 'I''m no-tat home.', '/audio/patterns/linking-cv-notat-slow.mp3', '/audio/patterns/linking-cv-notat-fast.mp3', ARRAY['The "t" links to "at"', 'In American English, both t''s may become flaps', 'Creates very smooth connected speech'], 2, 45),

('linking-vv-goout', 'linking', 2, 'Vowel-Vowel Linking: go out', 'When two vowels meet, English adds a glide sound. "Go out" becomes "go-wout".', '/ɡoʊ aʊt/', '/ɡoʊ.waʊt/', 'Let''s go out tonight.', 'Let''s go-wout tonight.', '/audio/patterns/linking-vv-goout-slow.mp3', '/audio/patterns/linking-vv-goout-fast.mp3', ARRAY['A "w" glide appears between vowels', 'This happens when first vowel is /oʊ/, /uː/', 'Makes the transition smooth'], 3, 46),

('linking-vv-seeit', 'linking', 2, 'Vowel-Vowel Linking: see it', 'Between "ee" and a following vowel, a "y" glide appears: "see-yit".', '/siː ɪt/', '/siː.jɪt/', 'I can see it.', 'I can see-yit.', '/audio/patterns/linking-vv-seeit-slow.mp3', '/audio/patterns/linking-vv-seeit-fast.mp3', ARRAY['A "y" glide appears after "ee" sound', 'Happens with words ending in /iː/, /eɪ/', 'Listen: "I see it" → "I see-yit"'], 3, 47),

('linking-vv-doaway', 'linking', 2, 'Vowel-Vowel Linking: do away', '"Do away" gets a "w" glide: "do-waway".', '/duː əˈweɪ/', '/duː.wəˈweɪ/', 'Do away with it.', 'Do-waway with it.', '/audio/patterns/linking-vv-doaway-slow.mp3', '/audio/patterns/linking-vv-doaway-fast.mp3', ARRAY['The "oo" sound connects with a "w" glide', 'Natural way to connect round vowels', 'Try it: "Who is" → "Who-wiz"'], 3, 48),

('linking-r-heris', 'linking', 2, 'Linking R: her eyes', 'A linking "r" appears when a word ending in "r/re" is followed by a vowel.', '/hɜːr aɪz/', '/hɜː.raɪz/', 'Her eyes are blue.', 'Her-eyes are blue.', '/audio/patterns/linking-r-heris-slow.mp3', '/audio/patterns/linking-r-heris-fast.mp3', ARRAY['The "r" connects to the following vowel', 'Common in British and American English', 'Also: "far away" → "far-away"'], 3, 49),

('linking-r-forinstance', 'linking', 2, 'Linking R: for instance', 'The "r" in "for" links to "instance".', '/fɔːr ˈɪnstəns/', '/fɔː.rˈɪnstəns/', 'For instance, this one.', 'For-instance, this one.', '/audio/patterns/linking-r-forinstance-slow.mp3', '/audio/patterns/linking-r-forinstance-fast.mp3', ARRAY['The final "r" links to the vowel', 'Creates smooth professional speech', 'Same pattern: "or else" → "or-else"'], 3, 50);
